# Generated by Django 2.2 on 2019-06-01 11:16

import challenge.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[(challenge.models.StatesClass('SUCCESS'), 'SUCCESS'), (challenge.models.StatesClass('FAILED'), 'FAILED'), (challenge.models.StatesClass('TIMEOUT'), 'TIMEOUT'), (challenge.models.StatesClass('IN_PROGRESS'), 'IN_PROGRESS'), (challenge.models.StatesClass('TO_DO'), 'TO_DO')], default='TO_DO', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('UUID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Customer')),
            ],
        ),
    ]
