# Generated by Django 2.2 on 2019-06-01 10:17

import challenge.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(challenge.models.States(1), 1), (challenge.models.States(2), 2), (challenge.models.States(3), 3), (challenge.models.States(4), 4), (challenge.models.States(5), 5)], default=challenge.models.States(5), max_length=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('UUID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Customer')),
            ],
        ),
    ]
